[Issue-267] Add Spark Connector Examples
pravega/pravega-samples pull request #268
Opened 2020-10-22 14:43 UTC by youminhan

Signed-off-by: Youmin Han [Youmin.Han@dell.com](Youmin.Han@dell.com)

**Change log description**
Add code examples to demonstrate the capabilities of Pravega as a data stream storage system for Apache Spark. 

**Purpose of the change**
Fixes #267 

**What the code does**
It has various examples using the spark connector to write the event to the Pravega stream or read from it. 
Please see the `README.md` folder for details. 

**How to verify it**
See the `README.md` in `spark-connector-examples` folder for details.

2020-10-23 17:31 UTC, claudiofahey approved these changes

2020-10-28 09:58 UTC, RaulGracia requested changes
Thanks for the contribution @youminhan. Please, could you change this PR to target branch `dev` instead of `master`? In this repo, the PRs are merged into `dev` until the release time, at which we merge `dev` into `master`. Please, see https://github.com/pravega/pravega-samples/wiki.

2020-10-29 13:28 UTC, youminhan commented
> Thanks for the contribution @youminhan. Please, could you change this PR to target branch `dev` instead of `master`? In this repo, the PRs are merged into `dev` until the release time, at which we merge `dev` into `master`. Please, see https://github.com/pravega/pravega-samples/wiki.

Hey @RaulGracia , thank you for letting me know the policy for PRs. I just modified the target branch to `dev`. Let me know if there's anything I need to make changes. Thanks.

2020-12-07 09:53 UTC, RaulGracia requested changes

2020-12-07 09:53 UTC, RaulGracia commented on spark-connector-examples/README.md
> +git checkout r0.7
Should this be `r0.8`?

2020-12-07 09:53 UTC, RaulGracia commented on spark-connector-examples/README.md
> +that is started with the Spark job ("--master local[2]").
Nit: maybe is better to use `this format` for --master local[2].

2020-12-07 09:53 UTC, RaulGracia commented on spark-connector-examples/README.md
> +The file *sample_data.json" has the following conents:
*sample_data.json" has inconsistent format.

2020-12-07 09:53 UTC, RaulGracia commented on spark-connector-examples/build.gradle
> +apply plugin: "java"
None of these files contains the Pravega license header. Please add them, according to the format of this repo: https://github.com/pravega/pravega

2020-12-07 09:53 UTC, RaulGracia commented on spark-connector-examples/run_pyspark_app.sh
> +#!/usr/bin/env bash
Same for script files regarding license header.

2020-12-07 09:53 UTC, RaulGracia commented on spark-connector-examples/src/main/python/batch_file_to_pravega.py
> +from pyspark.sql import SparkSession
Missing license header.

2020-12-07 09:53 UTC, RaulGracia commented on spark-connector-examples/src/main/scala/io/pravega/example/spark/StreamPravegaToConsole.scala
> +package io.pravega.example.spark
Missing license header.

2020-12-07 09:56 UTC, RaulGracia commented
@youminhan @claudiofahey in general it LGTM, but there are mainly small doc improvements and missing license headers that require fixing.
Also, please add a section in the main README of the project for the Spark connector samples. Please, follow the structure of the other sections, in which we briefly describe the purpose of the folder and a table with the available samples and links.

2020-12-07 19:25 UTC, youminhan commented on spark-connector-examples/README.md
> +git checkout r0.7
Yep. Fixed it.

2020-12-07 19:27 UTC, youminhan commented
@RaulGracia Thank you for taking the time to review our spark connector examples. I have updated the README and license header based on your suggestions. Please let me know if there's anything we need to change. Thanks.

2020-12-09 17:41 UTC, RaulGracia approved these changes
LGTM

2020-12-09 17:42 UTC, merged