[Issue-295] Add Python code examples in the Flink SQL samples
pravega/pravega-samples pull request #296
Opened 2021-07-15 09:13 UTC by thekingofcity

**Change log description**
The pravega-flink-connector-sql-samples in scenarios only supports the java version. Adding a python version would help those from other backgrounds.

**Purpose of the change**
Fixes #295 

**What the code does**
Add a corresponding python version to the `pravega-flink-connector-sql-samples` in `scenarios`.

**How to verify it**
User could follow the `python.md` and complete the tutorial just as the java version.

2021-07-16 02:53 UTC, crazyzhou requested changes
I will retest again for a second round review, besides these comments, please change the target branch to `dev` instead of master.

2021-07-16 02:53 UTC, crazyzhou commented on scenarios/pravega-flink-connector-sql-samples/src/main/python/common.py
> +    'scan.reader-group.name' = '{reader_group_name}',
This line forcing the RG is not recommended now, we can remove this.

2021-07-16 03:33 UTC, thekingofcity commented on scenarios/pravega-flink-connector-sql-samples/python.md
> +3. Python version 3.8
Until now, the `apache-flink` package only supports python from 3.6 to 3.8
https://pypi.org/project/apache-flink/#files

2021-07-16 03:36 UTC, thekingofcity commented on scenarios/pravega-flink-connector-sql-samples/python.md
> +5. `pip install apache-flink 1.12.4`
Do we need to specify the `<flink version>` somewhere else in the document?

2021-07-16 03:38 UTC, thekingofcity commented on scenarios/pravega-flink-connector-sql-samples/python.md
> +6. (optional) Redirect the python you want to use to `python`:
It is a must to use python at version 3 and have `python` command pointing to it.
See https://ci.apache.org/projects/flink/flink-docs-release-1.12/dev/python/installation.html#environment-setup

2021-07-28 02:19 UTC, crazyzhou commented on scenarios/pravega-flink-connector-sql-samples/python.md
> +6. (optional) Redirect the python you want to use to `python`:
For all the python environment setup, we can directly refer to Flink document: https://ci.apache.org/projects/flink/flink-docs-stable/docs/dev/python/installation/

2021-07-28 03:35 UTC, crazyzhou requested changes
The python code needs to have license headers.

2021-08-04 08:06 UTC, crazyzhou requested changes

2021-08-04 08:06 UTC, crazyzhou commented on scenarios/pravega-flink-connector-sql-samples/python.md
> +    > flink run --python ./bin/popular_destination_query.py --pyFiles ./bin/common.py --jarfile ~/pravega-connectors-flink-1.11_2.12-0.9.1.jar
We need to generalize the connector version as `--jarfile <path/to/pravega-flink-connector>`

2021-08-04 08:06 UTC, crazyzhou commented on scenarios/pravega-flink-connector-sql-samples/python.md
> +
This also require Flink running, right?

2021-08-09 02:15 UTC, crazyzhou approved these changes
LGTM, if you can screenshot some of the results in the PR description or comment, it would be better.

2021-08-23 02:45 UTC, thekingofcity commented
After executing the `prepare_main` and `popular_taxi_vendor`, the result could be viewed at the Flink UI.

![image](https://user-images.githubusercontent.com/3353040/130382891-1bb45c78-5183-46a5-a242-ba859b157bb6.png)

2021-08-23 08:16 UTC, merged