[Issue-311] CDC demo
pravega/pravega-samples pull request #312
Opened 2021-10-27 08:56 UTC by thekingofcity

Signed-off-by: thekingofcity <3353040+thekingofcity@users.noreply.github.com>

**Change log description**
As Debezium supports Pravega by default, a CDC demo that preserves data in Pravega can be added to demonstrate what the workflow should be. And we can also have Flink as a downstream consumer that computes these data in a streaming way.

**Purpose of the change**
Fixes #311 

**What the code does**
Introduce a CDC demo involving Pravega, Debezium, and Flink.

**How to verify it**
The demo could run exactly as the README.md suggests.

2021-11-17 08:31 UTC, thekingofcity commented on scenarios/change-data-capture/datagen/Dockerfile
> +RUN pip install --no-cache-dir mysql-connector-python pravega===0.2.0 yfinance
The latest 0.3.1 version of pravega python client should fix most of the concerns.

2021-12-03 09:29 UTC, crazyzhou requested changes

2021-12-03 09:29 UTC, crazyzhou commented on scenarios/change-data-capture/docker-compose.yml
> +      sleep 60 &&
Instead of a static wait for, maybe having a health checker is better, like what is did in the Catalog demo PR.

2021-12-03 09:29 UTC, crazyzhou commented on scenarios/change-data-capture/README.md
> +This page demonstrates how to preserve the CDC (Change Data Capture) from Mysql into Pravega and consume them in Flink.
Please use `MySQL` instead of `Mysql` as it's a formal name.

2021-12-03 09:29 UTC, crazyzhou commented on scenarios/change-data-capture/README.md
> +- DataGen: the data generator. After the container is started, stock data from previous 5 days are pulled and updated to the Mysql. There were more than 1800 data points which should run at least hal
It looks confusing with both 5 days and half an hour if they do not know about the speedup we set. I think we can rephrase it in a more general way, like speeding up the changes of 5 days into half an hour.

2022-02-11 08:50 UTC, crazyzhou approved these changes
LGTM

2022-02-11 09:10 UTC, crazyzhou approved these changes
LGTM

2022-02-12 01:13 UTC, derekm requested changes
I have some suggested changes for language and grammar.

I also tested this against a docker image of 0.10.2-rc2, and it worked as-is.

2022-02-12 01:13 UTC, derekm commented on scenarios/change-data-capture/README.md
> +This command automatically starts all the containers defined in the docker compose configuration in the detached mode. Run `docker ps` if you wish to check whether the 7 containers are running proper
"This command automatically starts *in detached mode* all the containers defined in the docker compose configuration."

2022-02-12 01:13 UTC, derekm commented on scenarios/change-data-capture/README.md
> +We use Pravega as the streaming storage system which can preserve the continuous data stream, so the change data can be both written to and read from a durable, elastic and consistent place. Also, th
You may have a look at *the* [Pravega](https://cncf.pravega.io/) and [Debezium](https://debezium.io/) *homepages*.

2022-02-12 01:13 UTC, derekm commented on scenarios/change-data-capture/README.md
> +Now it's time to consume them.
"Now it's time to consume *the data*."

2022-02-14 03:16 UTC, thekingofcity commented
> I have some suggested changes for language and grammar.

Thanks for the suggestion. I updated the readme.

> I seem to get duplicate results when I do a simple `SELECT * FROM stock;`. What causes this?

I'm not able to reproduce the *duplicate results*. Do you have any screenshots?

2022-02-14 16:10 UTC, derekm commented on scenarios/change-data-capture/docker-compose.yml
> +    image: fyang86/pravega:0.10.1-65df3fbd-set-published-ip
0.10.2 rc1 docker image works great in this sample

2022-02-16 09:57 UTC, crazyzhou commented
@derekm We have published the images to the official Pravega dockerhub and made the changes in the compose file accordingly. We tested it ok, and this PR is ready to review now except waiting for the Pravega 0.10.2 image.

2022-05-17 09:40 UTC, RaulGracia commented on scenarios/change-data-capture/docker-compose.yml
> +    image: fyang86/pravega:0.10.1-65df3fbd-set-published-ip
@crazyzhou please, change the above image by the official ones now that both 0.10.2 and 0.11.0 images are released.

2022-05-17 10:08 UTC, crazyzhou commented on scenarios/change-data-capture/docker-compose.yml
> +    image: fyang86/pravega:0.10.1-65df3fbd-set-published-ip
Fixed in [daf214e](https://github.com/pravega/pravega-samples/pull/312/commits/daf214e45d67a7e9195cb144f689bb82fef118de)

2022-05-17 13:26 UTC, RaulGracia approved these changes

2022-05-20 14:09 UTC, derekm approved these changes
works well for me!

2022-05-20 14:19 UTC, merged